### ISSUE TITLE
xcomp

### ISSUE THREAD

**Issue by CatalinaMaranduc** [roTreebankUD/ud-conversion-issues#10]
Da! salut ideea de a adnota astfel nu numai el.pred ci și n.pred subordonat de alte verbe copulative decât a fi pentru că sunt multe și unele controversate, altele polisemantice și copulative doar la un număr de sens, ”reprezintă” de pildă; apoi dacă le trecem la diateza pasivă, mă rog, scuze pentru viziunea mea transformaționalistă rezultă structuri cu el.pred.
”el este numit președinte” sau mai știu eu ce.

**Comment by radsimu** [comment]
eu nu inteleg...

**Comment by CatalinaMaranduc** [comment]
ei bine, n.pred în treebank-ul nostru apare subordonat de vreo 15 verbe copulative pe care ei nu le recunosc ca atare deci o sa il adnotam ca și pe el.pred. cu xcomp nici aici nu e bai, iti trec in tabel. unul dintre VC era a se numi de unde și exemplul, Asta se numește prostie prostie=n.pred., dar Asta este numită prostie nu mai era n.pred ci el.pred, pentru că verbele copulative sunt copulative într-un anumit sens și la o anumită diateză.

**Comment by verginicabm** [comment]
Altfel spus: numai unul/unele dintre sensurile unui verb este/sunt copulative, nu neaparat toate(exceptie: a deveni, care e mereu copulativ, desi in UD asta nu se va vedea). 
Apoi, sensuri diferite pot avea sintaxa diferita. Asa e cu "a numi" exemplificat de Catalina.

**Comment by CatalinaMaranduc** [comment]
braavo, așa e, ai înțeles.
de fapt, scuze, eu lucrez la DLR pt că mă scoate din sărite și vreau să
termin cu el și mă grăbesc, nu explic frumos scriu prea prescurtat.
profesorul meu Coteanu zicea că pentru o persoană inteligentă dacă nu
înțelege înseamnă că nu are ce.
dacă ne apucăm să discutăm care e VC și care nu, intrăm în discuții
nesfârșite. mai bine lăsăm așa, doar verbul a fi pt că tot e și auxiliar și
s-a obișnuit deja să stea atârnat.

2015-03-04 21:21 GMT+02:00 verginicabm notifications@github.com:
