### ISSUE TITLE
expl

### ISSUE THREAD

**Issue by CatalinaMaranduc** [roTreebankUD/ud-conversion-issues#13]
urmează ca această relație să fie folosită direct dacă avem subiect repetat.
Marius a venit el însuși. el=expl
sau ca subclasificare dacă avem complemente repetate:
l-am strigat pe Marius. l=dobj:expl
i-am spus lui Marius. i=iobj:expl
Ar fi mai coerent dacă și prima ar fi nsubj:expl, dar am impresia că alții adnotează subiectul repetat ca expl.

**Comment by radsimu** [comment]
Inteleg ca aici vrei sa propunem doua relatii noi? dobj:expl si iobj:expl? Cum s-a rezolvat in alte limbi pt complemente repetate?

**Comment by CatalinaMaranduc** [comment]
nu, astea nu trebuie propuse, sunt deja rezolvate în alte limbi, doar că mă
miram de ce subuectul e expl și complementele sunt subdiviziuni dar nu
deranjează.

**Comment by verginicabm** [comment]
Pt Radu: Cliticele care dubleaza dobj si iobj sunt "exlp".

**Comment by CatalinaMaranduc** [comment]
iar tu cred că nu ai trecut in tabel subiectul repetat care e expl simplu
ori sunt eu prea adormita cand ma uit.

**Comment by verginicabm** [comment]
Nu, asta nu e trecut deocamdata in tabelul nostru.

**Comment by CatalinaMaranduc** [comment]
pai da, și propoziția predicativă suplimentară care e dep
nu știu unde am văzut, o să caut,
așa ți-am răspuns la capitolul ALTELE?

**Comment by CatalinaMaranduc** [comment]
scz nu suplimentară, aia e xcomp, doar predicativă e dep.
sunt năucă la ora asta, nu am citate cu acont și tre să caut cu
concordanțierul, apoi să le caut siglele în noua bibliografie și să caut
pagina în noile ediții pt. că șefa a bulibășit toate.

2015-03-04 21:30 GMT+02:00 Catalina Maranduc catalinamaranduc@gmail.com:
