### ISSUE TITLE
subordonate relative

### ISSUE THREAD

**Issue by verginicabm** [roTreebankUD/ud-conversion-issues#2]
Numesc subordonate relative propozitiile subordonate introduse de un element relativ: pronume, adjectiv, adverb.
Dintre limbile care au aderat la UD, engleza, finlandeza, greaca, irlandeza si suedeza marcheaza subordonatele relative cu o eticheta aparte: acl:relcl. Dupa cum se deduce din nume, este un subtip al lui acl.
Intrebarea este: avem nevoie neaparat de aceasta relatie?
Sa tinem cont de faptul ca subordonatele relative sunt usor de identificat automat prin cautarea elementului relativ, fie printr-o metoda ce foloseste elemente lexicale, fie elemente morfologice.
In plus, exista subordonate relative care indeplinesc si alte functii sintactice, nu doar acl. Ele nu vor fi marcate ca subtip al relatiilor respective.

**Comment by CatalinaMaranduc** [comment]
Sunt de acord; nu putem marca în acest fel subiective, completive directe, predicative sau mai știu eu ce introduse prin pronume relative, deci ne putem lipsi de a marca astfel atributivele.
Altă problemă e că eu am văzut la exemple că marchează așa doar relativele introduse prin pronume sau adjectiv, pe când adverbul relativ (ex. when) îl adnotează ca mark de parcă ar fi conjuncție. Cred că noi putem adnota mai corect de atât !!! sper să nu fie interzis.
