### ISSUE TITLE
verbe la diateza reflexivă

### ISSUE THREAD

**Issue by CatalinaMaranduc** [roTreebankUD/ud-conversion-issues#3]
După cum am observat, label mark. se referă la conjuncții subordonatoare sau prepoziții care introduc părți de vorbire care nu au case.
Totuși, pentru că noi avem neapărată nevoie de a marca reflexivul verbelor care e relevant pentru selecțiile dependențelor lor, propun să scriem mark:refl.

**Comment by verginicabm** [comment]
In mostra de treebank cehesc, am gasit utilizarea etichetei "compound:reflex" pt pronumele reflexive fara functie sintactica (atat cu val refl, cat si cu val reciproca). Daca pron reflexiv are fct sint, el va fi dobj sau iobj. Daca are val posesiva (dativul posesiv), cred ca este "nmod:poss". Dar aici nu sunt sigura, pt ca nu am gasit ceva care sa semene cu romana. Propun sa semnalez la UD exemplele noastre.
Daca pron refl este marca a diat refl-pasive, l-am gasit etichetat ca "auxpass:reflex".

**Comment by CatalinaMaranduc** [comment]
am vazut in tabelul tau aceste etichete și tocmai te intrebam daca le-ai gasit undeva, dacă da, atunci e perfect, le vom adopta, sunt funcționabile. e mai bine sa folosim o etichetă deja existentă nu avem de ce să propunem una nouă.

**Comment by verginicabm** [comment]
Deci: 
- pt reflexiv folosim "compound:reflex"
- pt pron refl marca a diat refl-pas folosim "auxpass:reflex"
- pt Dat pos intrebam.
